apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: service-broker-dino-service
  namespace: dino-instance 
spec:
  clusterServiceClassExternalName: Service-1
  clusterServicePlanExternalName: plan-1
  parameters:
    namespace: test-ns2
    podname: pod-demo-1
